
GENRE_PACKS = {

    "sci_fi": {
        "ambienti": [
            "relitto orbitale", "foresta aliena", "stazione orbitale",
            "città sommersa", "canyon vivente", "pianeta-tempesta",
            "anello orbitale spezzato", "campo di asteroidi abitato",
            "struttura megascala aliena", "laboratorio fuori fase",
            "porto franco interstellare", "carovana nomade del vuoto",
            "arca generazionale deviata", "monastero quantistico",
            "cantiere di terraformazione incompiuto", "cimitero di sonde automatiche",
            "colonia mineraria scavata nel ghiaccio", "mercato orbitale clandestino",
        ],
        "minacce": [
            "contaminazione mentale", "collasso ambientale", "ambiente planetario ostile",
            "creatura", "anomalia gravitazionale", "infestazione biologica",
            "parassita simbiotico", "arma automatizzata fuori controllo", "alterazione temporale",
            "sciame di microsonde", "setta tecnomistica", "rivolta di coloni",
            "crisi diplomatica", "memoria sintetica corrotta", "rete di sorveglianza predittiva",
            "carestia energetica", "fenomeno cosmico incomprensibile", "contrabbandieri iperspaziali",
            "giurisdizione ostile", "frattura culturale tra umani e post-umani",
        ],
        "obiettivi": [
            "recupero", "salvataggio", "fuga", "sabotaggio", "esplorazione",
            "contatto", "ricognizione", "bonifica", "scorta",
            "negoziazione", "evacuazione", "quarantena", "mediazione",
        ],
        "toni": [
            "sopravvivenza tesa", "mistero archeologico",
            "thriller militare", "contatto ambiguo",
            "meraviglia ostile", "horror biologico",
            "noir spaziale", "dramma politico", "tragedia scientifica", "odissea metafisica",
        ],
        "twists": [
            "la missione originale è falsa",
            "rivali già sul posto",
            "il bersaglio è già contaminato",
            "il tempo scorre diversamente",
            "l'ambiente è un archivio vivente",
            "la colonia nasconde un patto inconfessabile",
            "la minaccia sta solo reagendo a un torto umano",
            "qualcuno sta inscenando il disastro per coprire una fuga",
            "il vero obiettivo è una persona, non un oggetto",
            "la frontiera legale conta più della forza bruta",
            "il contatto cercato vi conosce già",
            "la risorsa contesa è cosciente",
            "la missione richiede di scegliere chi lasciare indietro",
        ],
        "blacklist_base": [
            "corridoi metallici standard",
            "allarmi rossi lampeggianti",
            "terminali generici",
            "IA cattiva senza motivazione",
            "parassita generico spiegato in due righe",
            "stazione spaziale indistinguibile da tutte le altre",
        ],
        "narrative_blacklist": [
            "filamenti o micelio che si infiltrano ovunque",
            "personaggio che si fonde con un'entità o viene assorbito",
            "rete biologica che controlla menti",
            "struttura narrativa di contagio/assorbimento/fusione",
            "villain IA che vuole liberarsi dai vincoli umani",
            "scienziato pazzo che ha perso il controllo dell'esperimento",
            "l'intera colonia è già compromessa dal primo turno",
            "ozono bruciato come dettaglio sensoriale ricorrente",
            "luci d'emergenza arancioni che gettano ombre",
            "corridoio tecnico come ambientazione predefinita",
            "contatore/conto alla rovescia sul polso con display pulsante",
            "obiettivo bipartito 'A oppure B' con scelta morale",
            "lista di nomi scritti a mano su paratie o pannelli",
            "dialogo tramite interfono disturbato come unico contatto con comandi",
        ],
        "families": {
            "frontiera": {
                "ambienti": ["carovana nomade del vuoto", "colonia mineraria scavata nel ghiaccio", "campo di asteroidi abitato"],
                "minacce": ["contrabbandieri iperspaziali", "carestia energetica", "ambiente planetario ostile", "rivolta di coloni"],
                "obiettivi": ["scorta", "evacuazione", "recupero", "mediazione"],
                "toni": ["sopravvivenza tesa", "noir spaziale"],
                "twists": ["la minaccia sta solo reagendo a un torto umano", "la missione richiede di scegliere chi lasciare indietro"],
            },
            "politico": {
                "ambienti": ["porto franco interstellare", "mercato orbitale clandestino", "arca generazionale deviata"],
                "minacce": ["crisi diplomatica", "giurisdizione ostile", "frattura culturale tra umani e post-umani", "rete di sorveglianza predittiva"],
                "obiettivi": ["negoziazione", "mediazione", "contatto", "quarantena"],
                "toni": ["dramma politico", "noir spaziale"],
                "twists": ["la frontiera legale conta più della forza bruta", "il vero obiettivo è una persona, non un oggetto"],
            },
            "metafisico": {
                "ambienti": ["monastero quantistico", "laboratorio fuori fase", "struttura megascala aliena"],
                "minacce": ["fenomeno cosmico incomprensibile", "alterazione temporale", "contaminazione mentale"],
                "obiettivi": ["contatto", "esplorazione", "ricognizione"],
                "toni": ["odissea metafisica", "meraviglia ostile", "tragedia scientifica"],
                "twists": ["il contatto cercato vi conosce già", "l'ambiente è un archivio vivente", "il tempo scorre diversamente"],
            },
            "biohorror": {
                "ambienti": ["cantiere di terraformazione incompiuto", "foresta aliena", "città sommersa"],
                "minacce": ["infestazione biologica", "parassita simbiotico", "creatura", "contaminazione mentale"],
                "obiettivi": ["bonifica", "quarantena", "salvataggio"],
                "toni": ["horror biologico", "sopravvivenza tesa"],
                "twists": ["il bersaglio è già contaminato", "la risorsa contesa è cosciente"],
            },
            "archeologico": {
                "ambienti": ["relitto orbitale", "cimitero di sonde automatiche", "anello orbitale spezzato"],
                "minacce": ["memoria sintetica corrotta", "anomalia gravitazionale", "arma automatizzata fuori controllo"],
                "obiettivi": ["recupero", "esplorazione", "ricognizione"],
                "toni": ["mistero archeologico", "tragedia scientifica"],
                "twists": ["rivali già sul posto", "qualcuno sta inscenando il disastro per coprire una fuga", "la missione originale è falsa"],
            },
        },
    },

    "fantasy": {
        "ambienti": [
            "rovine sommerse", "foresta stregata", "fortezza in rovina",
            "cripta dimenticata", "montagna sacra", "città maledetta",
            "biblioteca infinita", "città sospesa", "bosco mutante",
            "torre spezzata", "regno sotterraneo", "cimitero delle divinità",
            "deserto di vetro", "fortezza scavata nel tronco del mondo",
            "corte lunare decaduta", "officina dei draghi",
        ],
        "minacce": [
            "bestia antica", "culto proibito", "maledizione",
            "non morti", "spiriti vendicativi", "magia instabile",
            "divinità decaduta", "artefatto senziente",
            "cavaliere corrotto", "invasione planare",
            "carestia sacra", "casata rivale", "faglia tra i regni", "oracolo impazzito",
        ],
        "obiettivi": [
            "recupero", "salvataggio", "fuga", "sabotaggio",
            "contatto", "purificazione", "ricognizione", "scorta",
            "mediazione", "consacrazione", "caccia", "sigillo",
        ],
        "toni": [
            "epica cupa", "fiaba nera", "orrore gotico",
            "mistero sacrale", "avventura tragica",
            "meraviglia malinconica", "decadenza regale", "favola crudele",
        ],
        "twists": [
            "profezia incompleta",
            "sacrificio necessario",
            "l'eroe è la minaccia",
            "la magia è in esaurimento",
            "il mondo è artificiale",
            "il mostro custodisce davvero il confine",
            "il regno dipende da un peccato taciuto",
            "la reliquia rifiuta i puri e sceglie gli indegni",
            "la stirpe perduta è già presente nel gruppo",
        ],
        "blacklist_base": [
            "taverna iniziale generica",
            "goblin casuali",
            "porta con chiave banale",
            "profezia risolta in modo banale",
            "re malvagio senza storia",
        ],
        "narrative_blacklist": [
            "l'eroe scopre di essere il prescelto della profezia",
            "il gruppo visita la taverna prima di partire per l'avventura",
            "il villain è malvagio perché è corrotto da un artefatto oscuro senza storia",
            "la missione inizia con un mandante che sparisce subito",
            "la minaccia finale è un portale interdimensionale da chiudere",
        ],
        "families": {
            "mitico": {
                "ambienti": ["montagna sacra", "cimitero delle divinità", "città sospesa"],
                "minacce": ["divinità decaduta", "invasione planare", "artefatto senziente"],
                "obiettivi": ["contatto", "purificazione", "recupero"],
                "toni": ["mistero sacrale", "avventura tragica"],
                "twists": ["profezia incompleta", "il mondo è artificiale"],
            },
            "gotico": {
                "ambienti": ["cripta dimenticata", "fortezza in rovina", "città maledetta"],
                "minacce": ["non morti", "maledizione", "spiriti vendicativi"],
                "obiettivi": ["salvataggio", "purificazione", "fuga"],
                "toni": ["orrore gotico", "epica cupa"],
                "twists": ["sacrificio necessario", "l'eroe è la minaccia"],
            },
            "selvaggio": {
                "ambienti": ["foresta stregata", "bosco mutante", "rovine sommerse"],
                "minacce": ["bestia antica", "magia instabile", "culto proibito"],
                "obiettivi": ["ricognizione", "scorta", "salvataggio"],
                "toni": ["fiaba nera", "avventura tragica"],
                "twists": ["la magia è in esaurimento", "profezia incompleta"],
            },
            "occulto": {
                "ambienti": ["biblioteca infinita", "torre spezzata", "regno sotterraneo"],
                "minacce": ["culto proibito", "artefatto senziente", "cavaliere corrotto"],
                "obiettivi": ["recupero", "sabotaggio", "contatto"],
                "toni": ["mistero sacrale", "epica cupa"],
                "twists": ["il mondo è artificiale", "l'eroe è la minaccia"],
            },
        },
    },

    "mystery_horror": {
        "ambienti": [
            "villa isolata", "paese nebbioso", "ospedale abbandonato",
            "abbazia sconsacrata", "isola battuta dalla pioggia",
            "teatro chiuso", "manicomio in rovina",
            "hotel con stanze mancanti", "casa che si modifica",
            "metropolitana chiusa", "archivio municipale sigillato",
            "collegio femminile dismesso", "clinica termale in disuso",
        ],
        "minacce": [
            "presenza invisibile", "setta locale", "contagio mentale",
            "verità sepolta", "sdoppiamento identitario",
            "anomalia temporale", "entità imitatrice",
            "memoria corrotta", "osservatore nascosto",
            "ricatto spirituale", "colpa collettiva", "testimonianza impossibile",
        ],
        "obiettivi": [
            "indagine", "salvataggio", "fuga",
            "contatto", "bonifica", "protezione",
            "esorcismo", "ricostruzione", "contenimento",
        ],
        "toni": [
            "suspense opprimente", "orrore psicologico",
            "angoscia crescente", "claustrofobia",
            "paranoia fredda", "tristezza contaminata",
        ],
        "twists": [
            "il colpevole è nel gruppo",
            "la vittima è viva",
            "il luogo reagisce",
            "qualcuno mente dall'inizio",
            "la minaccia vuole essere trovata",
            "l'unica testimonianza vera è quella del folle",
            "la casa protegge qualcuno, non qualcosa",
            "il rituale serviva a contenere, non evocare",
        ],
        "blacklist_base": [
            "fantasma generico",
            "diario trovato per caso",
            "casa infestata standard",
            "jump scare come unica paura",
        ],
        "narrative_blacklist": [
            "il fantasma vuole vendetta per qualcosa di ovvio",
            "la rivelazione finale è che i protagonisti sono morti dall'inizio",
            "il culto è malvagio senza motivazione interna comprensibile",
            "la struttura narrativa di 'tutti nascondono lo stesso segreto banale'",
            "il mostro è metafora della malattia mentale del protagonista",
        ],
        "families": {
            "investigativo": {
                "ambienti": ["villa isolata", "teatro chiuso", "hotel con stanze mancanti"],
                "minacce": ["verità sepolta", "osservatore nascosto", "qualcuno mente dall'inizio"],
                "obiettivi": ["indagine", "protezione"],
                "toni": ["suspense opprimente", "claustrofobia"],
                "twists": ["la vittima è viva", "il colpevole è nel gruppo"],
            },
            "psicologico": {
                "ambienti": ["manicomio in rovina", "ospedale abbandonato", "casa che si modifica"],
                "minacce": ["sdoppiamento identitario", "memoria corrotta", "contagio mentale"],
                "obiettivi": ["indagine", "fuga", "bonifica"],
                "toni": ["orrore psicologico", "angoscia crescente"],
                "twists": ["qualcuno mente dall'inizio", "la minaccia vuole essere trovata"],
            },
            "occulto": {
                "ambienti": ["abbazia sconsacrata", "paese nebbioso", "isola battuta dalla pioggia"],
                "minacce": ["presenza invisibile", "setta locale", "anomalia temporale"],
                "obiettivi": ["contatto", "bonifica", "salvataggio"],
                "toni": ["suspense opprimente", "orrore psicologico"],
                "twists": ["il luogo reagisce", "la minaccia vuole essere trovata"],
            },
            "storico": {
                "ambienti": [
                    "città medievale", "castello in rovina", "monastero isolato",
                    "borgo rinascimentale", "porto mercantile del '600", "corte nobiliare",
                    "villaggio durante la peste", "torre dell'inquisizione", "mercato coloniale",
                ],
                "minacce": ["culto segreto", "congiura nobiliare", "maledizione antica", "eresia perseguitata", "setta alchemica"],
                "obiettivi": ["indagine", "protezione", "fuga", "salvataggio", "ricostruzione"],
                "toni": ["suspense opprimente", "paranoia fredda", "tristezza contaminata"],
                "twists": ["il colpevole è nel gruppo", "qualcuno mente dall'inizio", "la vittima è viva"],
                "blacklist_add": ["smartphone", "computer", "pistola a proiettili", "automobile", "elettricità"],
                "era": "storica",
            },
        },
    },

    "ww2": {
        "ambienti": [
            "villaggio occupato", "linea del fronte",
            "trincee fangose", "città bombardata",
            "bunker sotterraneo", "ponte strategico",
            "fabbrica militare", "porto sotto attacco",
            "monastero requisito", "galleria ferroviaria alpina",
        ],
        "minacce": [
            "cecchini", "artiglieria", "raid aereo",
            "spie nemiche", "mine", "tradimento interno",
            "unità d'élite", "civili infiltrati", "linee di rifornimento spezzate",
        ],
        "obiettivi": [
            "difesa", "attacco", "ricognizione",
            "sabotaggio", "salvataggio", "resistenza",
            "estrazione", "tenuta della linea", "intercettazione",
        ],
        "toni": [
            "realismo crudo", "tensione costante",
            "eroismo tragico", "sopravvivenza",
            "stanchezza morale", "determinazione disperata",
        ],
        "twists": [
            "ordini sbagliati",
            "fuoco amico",
            "missione sacrificabile",
            "tradimento locale",
            "l'obiettivo tattico copre un crimine alleato",
            "i civili sanno più dei comandi",
        ],
        "blacklist_base": [
            "eroismo irrealistico",
            "nemici caricaturali",
            "gloria bellica senza costo umano",
        ],
        "narrative_blacklist": [
            "il soldato solitario che salva tutti da solo",
            "missione suicida con sopravvivenza garantita dei protagonisti",
            "il nemico è stupido o incompetente per permettere l'evasione",
            "rivelazione di un superweapon tedesco che cambia tutto",
        ],
        "families": {
            "resistenza": {
                "ambienti": ["villaggio occupato", "fabbrica militare", "porto sotto attacco"],
                "minacce": ["spie nemiche", "tradimento interno", "unità d'élite"],
                "obiettivi": ["resistenza", "sabotaggio", "salvataggio"],
                "toni": ["tensione costante", "eroismo tragico"],
                "twists": ["tradimento locale", "missione sacrificabile"],
            },
            "fronte": {
                "ambienti": ["linea del fronte", "trincee fangose", "città bombardata"],
                "minacce": ["artiglieria", "cecchini", "raid aereo", "mine"],
                "obiettivi": ["difesa", "attacco", "ricognizione"],
                "toni": ["realismo crudo", "sopravvivenza"],
                "twists": ["fuoco amico", "ordini sbagliati"],
            },
        },
    },

    "romance": {
        "ambienti": [
            "città europea", "caffè storico", "treno in viaggio",
            "hotel elegante", "festival estivo", "università",
            "piccolo paese", "studio artistico",
            "residenza sul lago", "set cinematografico", "atelier di moda",
        ],
        "minacce": [
            "incomprensione profonda", "distanza geografica",
            "passato irrisolto", "gelosia", "pressione sociale", "bugia nascosta",
            "dovere familiare", "ambizione incompatibile", "promessa non mantenuta",
        ],
        "obiettivi": [
            "avvicinamento", "riconciliazione",
            "dichiarazione", "comprensione",
            "scelta", "fiducia", "ritorno",
        ],
        "toni": [
            "dolce-amaro", "intimo",
            "nostalgico", "passionale",
            "brillante", "trattenuto", "elegante",
        ],
        "twists": [
            "amore reciproco tardivo",
            "uno mente",
            "scelta impossibile",
            "tempo sbagliato",
            "si stanno proteggendo mentendo",
            "il rivale sta cercando di salvarli da una verità",
            "la separazione era un atto d'amore mal compreso",
        ],
        "blacklist_base": [
            "amore a prima vista banale",
            "dramma artificiale",
            "triangolo amoroso meccanico",
        ],
        "narrative_blacklist": [
            "malinteso risolvibile con una conversazione di 30 secondi che non avviene mai",
            "l'antagonista sentimentale è pura cattiveria senza motivazione",
            "risoluzione con grande gesto romantico pubblico e imbarazzante",
            "i protagonisti si odiano e poi si amano senza transizione credibile",
        ],
        "families": {
            "nostalgico": {
                "ambienti": ["città europea", "caffè storico", "treno in viaggio"],
                "minacce": ["passato irrisolto", "distanza geografica", "tempo sbagliato"],
                "obiettivi": ["riconciliazione", "comprensione"],
                "toni": ["nostalgico", "dolce-amaro"],
                "twists": ["amore reciproco tardivo", "scelta impossibile"],
            },
            "sociale": {
                "ambienti": ["hotel elegante", "festival estivo", "università"],
                "minacce": ["pressione sociale", "gelosia", "bugia nascosta"],
                "obiettivi": ["avvicinamento", "dichiarazione"],
                "toni": ["passionale", "intimo"],
                "twists": ["uno mente", "scelta impossibile"],
            },
        },
    },

    "action": {
        "ambienti": [
            "grattacielo", "aeroporto internazionale", "autostrada",
            "treno in corsa", "metropolitana", "porto industriale",
            "base militare", "raffineria costiera", "cantiere navale",
        ],
        "minacce": [
            "terroristi", "mercenari",
            "bomba ad orologeria", "traditore interno",
            "inseguimento ad alta velocità", "attacco coordinato",
            "ricatto mediatico", "killer governativo", "sistema di sicurezza compromesso",
        ],
        "obiettivi": [
            "neutralizzazione", "salvataggio ostaggi",
            "fuga", "inseguimento", "protezione",
            "estrazione", "intercettazione", "contenimento",
        ],
        "toni": [
            "adrenalina pura", "ritmo serrato", "tensione continua",
            "sospetto operativo", "assedio urbano",
        ],
        "twists": [
            "bersaglio innocente",
            "nemico interno",
            "missione cambia in corsa",
            "tempo insufficiente",
            "la missione ufficiale serve a coprire un'estrazione sporca",
            "il bersaglio vi sta usando per arrivare a un terzo obiettivo",
            "l'attacco è una distrazione per un colpo altrove",
        ],
        "blacklist_base": [
            "esplosioni gratuite senza conseguenze",
            "eroe invincibile",
            "cattivo monolitico senza piano",
        ],
        "narrative_blacklist": [
            "singolo eroe che neutralizza decine di nemici senza rischio",
            "bomba disinnescata all'ultimo secondo sempre",
            "il piano del villain funziona solo perché spiega tutto ai protagonisti prima di agire",
            "inseguimento in auto risolto con una mossa spettacolare senza costi",
        ],
        "families": {
            "assedio": {
                "ambienti": ["grattacielo", "aeroporto internazionale", "base militare"],
                "minacce": ["terroristi", "attacco coordinato", "bomba ad orologeria"],
                "obiettivi": ["neutralizzazione", "salvataggio ostaggi", "protezione"],
                "toni": ["adrenalina pura", "tensione continua"],
                "twists": ["nemico interno", "tempo insufficiente"],
            },
            "caccia": {
                "ambienti": ["autostrada", "metropolitana", "porto industriale", "treno in corsa"],
                "minacce": ["mercenari", "inseguimento ad alta velocità", "traditore interno"],
                "obiettivi": ["fuga", "inseguimento", "neutralizzazione"],
                "toni": ["ritmo serrato", "adrenalina pura"],
                "twists": ["bersaglio innocente", "missione cambia in corsa"],
            },
        },
    },

    "detective_classico": {
        "ambienti": [
            "villa di campagna", "treno di lusso",
            "isola isolata", "hotel elegante",
            "residenza aristocratica", "yacht",
            "teatro d'opera privato", "stabilimento termale d'epoca",
        ],
        "minacce": [
            "omicidio", "avvelenamento",
            "alibi falso", "segreto di famiglia",
            "ricatto", "falso testamento", "furto simbolico",
        ],
        "obiettivi": [
            "indagine", "interrogatorio",
            "ricostruzione", "scoperta del colpevole",
            "smascheramento", "protezione del testimone",
        ],
        "toni": [
            "razionale e deduttivo", "eleganza distaccata", "sospetto crescente",
            "teatralita composta", "ironia sottile",
        ],
        "twists": [
            "tutti sono sospetti",
            "colpevole insospettabile",
            "alibi costruito ad arte",
            "più colpevoli",
            "il delitto nasconde una sostituzione d'identità",
            "la vittima aveva preparato la propria caduta",
            "il furto era il vero movente, non la morte",
        ],
        "blacklist_base": [
            "confessione casuale",
            "indizi troppo ovvi",
            "genio deduttivo infallibile senza lavoro sul campo",
        ],
        "narrative_blacklist": [
            "il colpevole si tradisce con un lapsus banale",
            "l'alibi crolla per un orologio fermo o una bugia ovvia",
            "il detective rivela tutto in un monologo finale davanti a tutti",
            "la vittima era cattiva quindi 'meritava' e il plot si chiude lì",
        ],
        "families": {
            "whodunit": {
                "ambienti": ["villa di campagna", "hotel elegante", "residenza aristocratica"],
                "minacce": ["omicidio", "alibi falso", "segreto di famiglia"],
                "obiettivi": ["indagine", "interrogatorio", "scoperta del colpevole"],
                "toni": ["razionale e deduttivo", "sospetto crescente"],
                "twists": ["colpevole insospettabile", "più colpevoli"],
            },
            "camera_chiusa": {
                "ambienti": ["treno di lusso", "yacht", "isola isolata"],
                "minacce": ["avvelenamento", "ricatto", "alibi falso"],
                "obiettivi": ["ricostruzione", "interrogatorio", "indagine"],
                "toni": ["eleganza distaccata", "sospetto crescente"],
                "twists": ["tutti sono sospetti", "alibi costruito ad arte"],
            },
        },
    },

}
