
# Stat su scala GURPS Lite (4ª ed.):
#   - 10 = umano medio; range tipico 8-14 (livello "Eccezionale" 75-100 pt).
#   - forza   = FO (anche PF base)
#   - agilita = DE
#   - intelligenza = IN (anche Volontà e Percezione)
#   - empatia = SA (vigore fisico GURPS; nel motore narrativo qui rappresenta anche reattività sociale)
#
# skills: nome -> livello effettivo (3d6 ≤ livello per riuscire).
#   Per riferimento, i livelli tipici a 75-100 pt sono 12-14.

ROLE_LIBRARY = {
    "sci_fi": [
        {"archetype": "marine", "role": "Marine",
         "stats": {"forza": 12, "agilita": 12, "intelligenza": 10, "empatia": 12},
         "skills": {"mira": 14, "combattere": 13, "strategia": 11, "curare": 11, "rapidita": 12, "intimidire": 11},
         "advantages": ["Riflessi da Combattimento"],
         "disadvantages": [],
         "base_items": ["fucile d'assalto", "armatura tattica"]},
        {"archetype": "scientist", "role": "Scienziata",
         "stats": {"forza": 10, "agilita": 10, "intelligenza": 13, "empatia": 11},
         "skills": {"scienze": 14, "analizzare": 13, "investigare": 13, "tecnologia": 12, "curare": 12},
         "base_items": ["scanner", "medkit"]},
        {"archetype": "technician", "role": "Tecnico",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 12, "empatia": 11},
         "skills": {"tecnologia": 14, "ingegneria": 13, "decifrare": 12, "manualita": 13, "investigare": 11},
         "base_items": ["toolkit", "scanner"]},
        {"archetype": "diplomat", "role": "Diplomatica",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 11, "empatia": 13},
         "skills": {"persuadere": 14, "intuire": 13, "etichetta": 13, "ingannare": 12, "comunicare": 13},
         "advantages": ["Carisma"],
         "disadvantages": [],
         "base_items": ["traduttore universale", "auricolare"]},
        {"archetype": "scout", "role": "Esploratore",
         "stats": {"forza": 11, "agilita": 13, "intelligenza": 11, "empatia": 10},
         "skills": {"furtivita": 14, "osservare": 13, "acrobazia": 12, "sopravvivere": 12, "pedinare": 12},
         "advantages": ["Sensi Acuti"],
         "disadvantages": [],
         "base_items": ["rampino", "scanner portatile"]},
        {"archetype": "pilot", "role": "Pilota",
         "stats": {"forza": 11, "agilita": 13, "intelligenza": 12, "empatia": 10},
         "skills": {"guidare": 14, "rapidita": 13, "tecnologia": 12, "mira": 12, "osservare": 11},
         "base_items": ["interfaccia neurale", "pistola"]},
    ],

    "fantasy": [
        {"archetype": "warrior", "role": "Guerriero",
         "stats": {"forza": 13, "agilita": 11, "intelligenza": 10, "empatia": 10},
         "skills": {"combattere": 14, "proteggere": 13, "intimidire": 12, "forzare": 12, "resistere": 13},
         "advantages": ["Duro da Uccidere", "Riflessi da Combattimento"],
         "disadvantages": [],
         "base_items": ["spada a due mani", "armatura pesante"]},
        {"archetype": "cleric", "role": "Chierica",
         "stats": {"forza": 10, "agilita": 10, "intelligenza": 12, "empatia": 13},
         "skills": {"curare": 14, "ispirare": 13, "cultura": 12, "persuadere": 12, "calmare": 12},
         "base_items": ["reliquia sacra", "kit erboristico"]},
        {"archetype": "rogue", "role": "Ladra",
         "stats": {"forza": 10, "agilita": 13, "intelligenza": 12, "empatia": 10},
         "skills": {"furtivita": 14, "scassinare": 13, "manualita": 12, "acrobazia": 12, "osservare": 12, "pedinare": 11},
         "base_items": ["arnesi da scasso", "pugnale avvelenato"]},
        {"archetype": "mage", "role": "Maga",
         "stats": {"forza": 8, "agilita": 10, "intelligenza": 13, "empatia": 12},
         "skills": {"cultura": 14, "decifrare": 13, "analizzare": 13, "scienze": 12, "intuire": 12},
         "base_items": ["grimorio", "focus arcano"]},
        {"archetype": "ranger", "role": "Ranger",
         "stats": {"forza": 11, "agilita": 12, "intelligenza": 11, "empatia": 11},
         "skills": {"mira": 13, "sopravvivere": 13, "furtivita": 12, "osservare": 12, "pedinare": 12, "curare": 11},
         "base_items": ["arco lungo", "corda"]},
        {"archetype": "penitent", "role": "Penitente",
         "stats": {"forza": 10, "agilita": 10, "intelligenza": 11, "empatia": 13},
         "skills": {"ispirare": 13, "curare": 12, "intuire": 12, "persuadere": 12, "resistere": 13},
         "base_items": ["reliquia", "flagello"]},
    ],

    "mystery_horror": [
        {"archetype": "detective", "role": "Detective",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 13, "empatia": 11},
         "skills": {"investigare": 14, "osservare": 13, "intuire": 12, "mira": 11, "intimidire": 11, "analizzare": 12},
         "base_items": ["taccuino", "pistola"]},
        {"archetype": "forensic", "role": "Analista Forense",
         "stats": {"forza": 8, "agilita": 10, "intelligenza": 13, "empatia": 11},
         "skills": {"analizzare": 14, "scienze": 13, "investigare": 13, "medicina": 12, "osservare": 12},
         "base_items": ["kit forense", "guanti in lattice"]},
        {"archetype": "medium", "role": "Medium",
         "stats": {"forza": 8, "agilita": 10, "intelligenza": 11, "empatia": 13},
         "skills": {"intuire": 14, "cultura": 13, "calmare": 12, "osservare": 12, "ispirare": 11},
         "base_items": ["amuleto protettivo", "taccuino"]},
        {"archetype": "bodyguard", "role": "Guardia del Corpo",
         "stats": {"forza": 12, "agilita": 12, "intelligenza": 10, "empatia": 10},
         "skills": {"combattere": 13, "proteggere": 14, "osservare": 12, "mira": 13, "intimidire": 12},
         "base_items": ["pistola", "torcia tattica"]},
        {"archetype": "journalist", "role": "Giornalista",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 12, "empatia": 12},
         "skills": {"investigare": 13, "persuadere": 13, "intuire": 12, "comunicare": 13, "osservare": 12},
         "base_items": ["registratore", "macchina fotografica"]},
    ],

    "ww2": [
        {"archetype": "rifleman", "role": "Fante",
         "stats": {"forza": 12, "agilita": 11, "intelligenza": 10, "empatia": 10},
         "skills": {"mira": 14, "combattere": 12, "rapidita": 11, "resistere": 12, "intimidire": 10},
         "base_items": ["fucile d'assalto", "elmetto"]},
        {"archetype": "medic", "role": "Medico da Campo",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 12, "empatia": 13},
         "skills": {"curare": 14, "medicina": 13, "calmare": 12, "ispirare": 11, "mira": 10},
         "base_items": ["kit medico", "pistola"]},
        {"archetype": "sniper", "role": "Cecchino",
         "stats": {"forza": 11, "agilita": 12, "intelligenza": 12, "empatia": 8},
         "skills": {"mira": 15, "furtivita": 13, "osservare": 13, "pedinare": 12, "rapidita": 11},
         "advantages": ["Sensi Acuti"],
         "disadvantages": [],
         "base_items": ["fucile di precisione", "mimetica"]},
        {"archetype": "radio_op", "role": "Radiotelegrafista",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 12, "empatia": 12},
         "skills": {"tecnologia": 13, "decifrare": 12, "comunicare": 13, "ingegneria": 11, "osservare": 11},
         "base_items": ["radio da campo", "pistola"]},
        {"archetype": "partisan", "role": "Partigiana",
         "stats": {"forza": 11, "agilita": 12, "intelligenza": 11, "empatia": 11},
         "skills": {"furtivita": 13, "combattere": 12, "demolire": 13, "sopravvivere": 12, "infiltrarsi": 12},
         "base_items": ["coltello", "esplosivi artigianali"]},
        {"archetype": "officer", "role": "Ufficiale",
         "stats": {"forza": 10, "agilita": 10, "intelligenza": 12, "empatia": 13},
         "skills": {"comandare": 14, "ispirare": 13, "strategia": 13, "etichetta": 11, "intimidire": 11},
         "advantages": ["Carisma"],
         "disadvantages": [],
         "base_items": ["radio", "pistola d'ordinanza"]},
    ],

    "romance": [
        {"archetype": "protagonist", "role": "Protagonista",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 11, "empatia": 13},
         "skills": {"intuire": 13, "comunicare": 13, "persuadere": 12, "intrattenere": 12, "osservare": 12},
         "base_items": ["taccuino personale", "fotografia"]},
        {"archetype": "confidant", "role": "Confidente",
         "stats": {"forza": 10, "agilita": 10, "intelligenza": 12, "empatia": 13},
         "skills": {"intuire": 14, "calmare": 13, "etichetta": 12, "persuadere": 12, "comunicare": 13},
         "base_items": ["telefono", "agenda"]},
        {"archetype": "romantic", "role": "Romantico Riluttante",
         "stats": {"forza": 11, "agilita": 11, "intelligenza": 12, "empatia": 11},
         "skills": {"persuadere": 12, "intrattenere": 12, "etichetta": 11, "intuire": 11, "osservare": 11},
         "base_items": ["lettera non spedita", "fotografia"]},
        {"archetype": "artist", "role": "Artista",
         "stats": {"forza": 8, "agilita": 11, "intelligenza": 12, "empatia": 13},
         "skills": {"intrattenere": 14, "intuire": 13, "cultura": 12, "manualita": 12, "comunicare": 12},
         "base_items": ["sketchbook", "macchina fotografica"]},
        {"archetype": "rival", "role": "Rivale",
         "stats": {"forza": 11, "agilita": 12, "intelligenza": 12, "empatia": 10},
         "skills": {"ingannare": 13, "persuadere": 12, "intuire": 12, "etichetta": 12, "intimidire": 11},
         "base_items": ["agenda", "telefono"]},
    ],

    "action": [
        {"archetype": "agent", "role": "Agente Speciale",
         "stats": {"forza": 11, "agilita": 12, "intelligenza": 12, "empatia": 10},
         "skills": {"mira": 13, "furtivita": 12, "combattere": 12, "ingannare": 12, "osservare": 12, "rapidita": 12},
         "base_items": ["pistola", "auricolare"]},
        {"archetype": "operative", "role": "Operativo",
         "stats": {"forza": 12, "agilita": 12, "intelligenza": 11, "empatia": 8},
         "skills": {"combattere": 14, "mira": 13, "demolire": 12, "rapidita": 12, "resistere": 12},
         "advantages": ["Riflessi da Combattimento"],
         "disadvantages": ["Animo Sanguinario"],
         "base_items": ["fucile automatico", "armatura tattica"]},
        {"archetype": "hacker", "role": "Hacker",
         "stats": {"forza": 8, "agilita": 11, "intelligenza": 13, "empatia": 11},
         "skills": {"tecnologia": 15, "decifrare": 14, "analizzare": 13, "ingegneria": 12, "investigare": 12},
         "base_items": ["laptop", "jammer elettronico"]},
        {"archetype": "field_medic", "role": "Medico sul Campo",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 12, "empatia": 12},
         "skills": {"curare": 14, "medicina": 13, "calmare": 12, "mira": 11, "rapidita": 11},
         "base_items": ["kit medico d'emergenza", "pistola"]},
        {"archetype": "driver", "role": "Conducente",
         "stats": {"forza": 11, "agilita": 13, "intelligenza": 11, "empatia": 10},
         "skills": {"guidare": 15, "rapidita": 13, "manualita": 12, "osservare": 12, "mira": 11},
         "base_items": ["strumenti da meccanico", "pistola"]},
    ],

    "detective_classico": [
        {"archetype": "detective", "role": "Investigatore",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 13, "empatia": 11},
         "skills": {"investigare": 14, "osservare": 13, "intuire": 13, "analizzare": 12, "persuadere": 11},
         "base_items": ["taccuino", "lente di ingrandimento"]},
        {"archetype": "assistant", "role": "Assistente",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 12, "empatia": 12},
         "skills": {"investigare": 12, "osservare": 12, "comunicare": 12, "manualita": 12, "intuire": 12},
         "base_items": ["taccuino", "macchina fotografica"]},
        {"archetype": "inspector", "role": "Ispettore",
         "stats": {"forza": 11, "agilita": 11, "intelligenza": 12, "empatia": 11},
         "skills": {"intimidire": 13, "investigare": 12, "comandare": 12, "mira": 12, "osservare": 12},
         "base_items": ["pistola", "distintivo ufficiale"]},
        {"archetype": "amateur", "role": "Dilettante Acuto",
         "stats": {"forza": 10, "agilita": 10, "intelligenza": 12, "empatia": 13},
         "skills": {"intuire": 14, "osservare": 13, "investigare": 12, "cultura": 12, "etichetta": 12},
         "base_items": ["taccuino", "ombrello"]},
        {"archetype": "journalist", "role": "Cronista",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 12, "empatia": 12},
         "skills": {"investigare": 13, "persuadere": 13, "intuire": 12, "comunicare": 13, "osservare": 12},
         "base_items": ["registratore", "macchina fotografica"]},
    ],

    # Tenuti per compatibilità con eventuali partite in corso
    "survival_horror": [
        {"archetype": "survivor", "role": "Sopravvissuta",
         "stats": {"forza": 11, "agilita": 11, "intelligenza": 11, "empatia": 11},
         "skills": {"sopravvivere": 13, "furtivita": 12, "resistere": 12, "osservare": 12, "mira": 11},
         "base_items": ["torcia", "coltello"]},
        {"archetype": "paramedic", "role": "Paramedico",
         "stats": {"forza": 10, "agilita": 10, "intelligenza": 12, "empatia": 13},
         "skills": {"curare": 14, "medicina": 13, "calmare": 12, "osservare": 11, "rapidita": 11},
         "base_items": ["kit medico", "torcia"]},
        {"archetype": "hunter", "role": "Cacciatore",
         "stats": {"forza": 12, "agilita": 11, "intelligenza": 10, "empatia": 10},
         "skills": {"mira": 14, "sopravvivere": 13, "furtivita": 12, "osservare": 12, "pedinare": 12},
         "base_items": ["fucile", "trappole"]},
        {"archetype": "scholar", "role": "Studiosa",
         "stats": {"forza": 8, "agilita": 10, "intelligenza": 13, "empatia": 12},
         "skills": {"cultura": 14, "analizzare": 13, "investigare": 13, "scienze": 12, "decifrare": 11},
         "base_items": ["manuale", "taccuino"]},
    ],
    "militare": [
        {"archetype": "rifleman", "role": "Fuciliere",
         "stats": {"forza": 12, "agilita": 11, "intelligenza": 10, "empatia": 10},
         "skills": {"mira": 13, "combattere": 12, "rapidita": 11, "resistere": 12, "osservare": 11},
         "base_items": ["fucile", "armatura leggera"]},
        {"archetype": "medic", "role": "Soccorritore",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 12, "empatia": 12},
         "skills": {"curare": 13, "medicina": 12, "calmare": 12, "rapidita": 11, "mira": 10},
         "base_items": ["kit medico", "pistola"]},
        {"archetype": "scout", "role": "Ricognitore",
         "stats": {"forza": 11, "agilita": 13, "intelligenza": 11, "empatia": 10},
         "skills": {"furtivita": 13, "osservare": 13, "sopravvivere": 12, "mia": 12, "pedinare": 12},
         "base_items": ["binocolo", "carabina"]},
        {"archetype": "officer", "role": "Ufficiale",
         "stats": {"forza": 10, "agilita": 10, "intelligenza": 12, "empatia": 13},
         "skills": {"comandare": 14, "ispirare": 12, "strategia": 12, "etichetta": 11, "intimidire": 11},
         "base_items": ["radio", "pistola"]},
    ],

    # ── Ruoli storici (medievale / rinascimentale / pre-industriale) ──────────
    # Usati quando theme_family == "storico" in mystery_horror o fantasy
    "mystery_horror_storico": [
        {"archetype": "inquisitor", "role": "Inquisitore",
         "stats": {"forza": 11, "agilita": 10, "intelligenza": 13, "empatia": 10},
         "skills": {"investigare": 14, "interrogare": 13, "intuire": 12, "intimidire": 12, "cultura": 11, "teologia": 12},
         "advantages": [],
         "disadvantages": ["Senso del Dovere"],
         "base_items": ["sigillo dell'autorità", "coltello da lavoro", "lume a olio"]},
        {"archetype": "scholar", "role": "Studioso",
         "stats": {"forza": 8, "agilita": 10, "intelligenza": 14, "empatia": 11},
         "skills": {"cultura": 14, "analizzare": 13, "storia": 13, "decifrare": 13, "occultismo": 12, "teologia": 12},
         "advantages": ["Memoria Fotografica"],
         "disadvantages": [],
         "base_items": ["pergamena e penna d'oca", "libro di testi", "sigillo personale"]},
        {"archetype": "knight", "role": "Cavaliere",
         "stats": {"forza": 13, "agilita": 11, "intelligenza": 10, "empatia": 11},
         "skills": {"combattere": 14, "proteggere": 13, "cavalcare": 13, "intimidire": 12, "etichetta": 11},
         "advantages": ["Riflessi da Combattimento"],
         "disadvantages": ["Senso del Dovere"],
         "base_items": ["spada lunga", "armatura di cuoio", "scudo"]},
        {"archetype": "herbalist", "role": "Erborista",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 12, "empatia": 13},
         "skills": {"curare": 14, "occultismo": 12, "intuire": 12, "seguire_tracce": 11, "calmare": 12},
         "advantages": [],
         "disadvantages": ["Segreto"],
         "base_items": ["borsa di erbe medicinali", "coltello da campo", "amuleto"]},
        {"archetype": "spy", "role": "Agente Segreto",
         "stats": {"forza": 10, "agilita": 12, "intelligenza": 12, "empatia": 12},
         "skills": {"furtivita": 13, "ingannare": 14, "recitazione": 13, "investigare": 12, "osservare": 12, "scassinare": 11},
         "advantages": [],
         "disadvantages": ["Segreto"],
         "base_items": ["pugnale nascosto", "inchiostro simpatico", "sigillo falso"]},
        {"archetype": "merchant", "role": "Mercante",
         "stats": {"forza": 10, "agilita": 11, "intelligenza": 12, "empatia": 13},
         "skills": {"persuadere": 14, "economia": 13, "intuire": 12, "etichetta": 12, "ingannare": 11, "comunicare": 12},
         "advantages": ["Contatti", "Ricchezza"],
         "disadvantages": [],
         "base_items": ["conto in monete", "lettera di credito", "coltello da cintura"]},
        {"archetype": "pilgrim", "role": "Pellegrino",
         "stats": {"forza": 11, "agilita": 10, "intelligenza": 11, "empatia": 13},
         "skills": {"sopravvivere": 13, "navigare": 12, "cultura": 12, "teologia": 13, "persuadere": 11, "calmare": 12},
         "advantages": ["Coraggio"],
         "disadvantages": [],
         "base_items": ["bordone da cammino", "mantello", "reliquia"]},
        {"archetype": "thief", "role": "Ladro",
         "stats": {"forza": 10, "agilita": 13, "intelligenza": 11, "empatia": 10},
         "skills": {"furtivita": 14, "scassinare": 13, "borseggiare": 13, "acrobazia": 12, "osservare": 12},
         "advantages": [],
         "disadvantages": ["Nemico"],
         "base_items": ["arnesi da scasso", "pugnale", "corda con uncino"]},
    ],
}

# ── Mappa theme_family → chiave ROLE_LIBRARY alternativa ─────────────────────
# Se il setting ha una famiglia storica, si usano ruoli appropriati al periodo.
THEME_FAMILY_ROLE_OVERRIDE: dict[str, str] = {
    "storico": "mystery_horror_storico",
}
